# Site settings
title: Jie_Y Blog
SEOTitle: Jie_Y的博客 | Jie_Y Blog
header-img: img/post-bg-desk.jpg
email: 1569425738@qq.com
description: " 做一个自己喜欢自己的人 "
keyword: "Jie_Y, Jie_Y Blog, Jie_Y的博客, hjyuan, Android, iOS, Apple, iPhone"
url: "https://hjyuan.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "强大是发自内心的!"
sidebar-avatar: /img/about-Jie_Y.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     JackY
github_username:    hjyuan
# facebook_username:  baiying.qiu.7
jianshu_username:   Jie_Y
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: Jie_Y

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: a29e14ea69cf11146973                            #生成的clientID
  clientSecret: 8eaf3d1813087329a5156799909cec2ecef7f21a    #生成的clientSecret
  repo: hjyuan.github.io    #仓库名称
  owner: hjyuan    #github用户名
  admin: hjyuan
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-133662155-1'            # Format: UA-xxxxxx-xx
ga_domain: hjyuan.xyz               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
